{{- $rlsNamespace := .Release.Namespace -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-controller" $rlsNamespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ $rlsNamespace }}
    name: {{ printf "%s-controller" $rlsNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-controller" $rlsNamespace }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-external-provisioner" $rlsNamespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ printf "%s-controller" $rlsNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-external-provisioner" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-csi-resizer" $rlsNamespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ printf "%s-controller" $rlsNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-csi-resizer" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-external-snapshotter" $rlsNamespace }}
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ printf "%s-controller" $rlsNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-external-snapshotter" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
