{{- $rlsNamespace := .Release.Namespace -}}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-leader-election" $rlsNamespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topolvm.fullname" . }}-controller
roleRef:
  kind: Role
  name: {{ printf "%s-leader-election" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-external-provisioner-cfg" $rlsNamespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topolvm.fullname" . }}-controller
roleRef:
  kind: Role
  name: {{ printf "%s-external-provisioner-cfg" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-external-resizer-cfg" $rlsNamespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ printf "%s-external-resizer-cfg" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s-external-snapshotter-leaderelection" $rlsNamespace }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ printf "%s-external-snapshotter-leaderelection" $rlsNamespace }}
  apiGroup: rbac.authorization.k8s.io
