apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-node" (include "topolvm.fullname" .) }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-node
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-node" (include "topolvm.fullname" .) }}
